services:
  - type: web
    name: agumentik-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MONGO_URI
        sync: false

  - type: static
    name: agumentik-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false